# Pre-commit configuration file to enforce code quality and style checks
repos:
  # Python code formatter Black for consistent, opinionated style
  - repo: https://github.com/psf/black
    rev: 24.3.0  # Use the latest stable version
    hooks:
      - id: black
        language_version: python3

  # General-purpose pre-commit hooks for maintaining clean code
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml

  # Python linter Flake8 to enforce PEP 8 style and detect code issues
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: ["--max-line-length=88"]
